Fix Scala.js support, source maps issue, update new command

diff --git a/skinny-blank-app/skinny b/skinny-blank-app/skinny
--- a/skinny-blank-app/skinny
+++ b/skinny-blank-app/skinny
@@ -17,7 +17,7 @@ fi
 
 function verify_skinny_project() {
   if [ "${current_project}" == "" ]; then
-    echo "Skinny applicaiton not found here!"
+    echo "Skinny application not found here!"
     exit 1
   fi
 }
@@ -53,16 +53,16 @@ function setup_scalajs() {
   setting_file="${current_dir}/project/_skinny_scalajs.sbt"
   if [ ! -f "${setting_file}" ]; then
     echo "resolvers += \"scala-js-release\" at \"http://dl.bintray.com/scala-js/scala-js-releases\"
-addSbtPlugin(\"org.scala-js\" % \"sbt-scalajs\" % \"0.6.4\")" > ${setting_file}
+addSbtPlugin(\"org.scala-js\" % \"sbt-scalajs\" % \"0.6.5\")" > ${setting_file}
 
 echo "lazy val scalajs = (project in file(\"src/main/webapp/WEB-INF/assets\")).settings(
   name := \"application\", // JavaScript file name
-  scalaVersion := \"2.11.6\",
+  scalaVersion := \"2.11.7\",
   unmanagedSourceDirectories in Compile <+= baseDirectory(_ / \"scala\"),
   libraryDependencies ++= Seq(
-    \"org.scala-js\" %%% \"scalajs-dom\"    % \"0.8.0\",
-    \"be.doeraene\"  %%% \"scalajs-jquery\" % \"0.8.0\",
-    \"org.monifu\"   %%  \"minitest\"       % \"0.11\" % \"test\"
+    \"org.scala-js\" %%% \"scalajs-dom\"    % \"0.8.2\",
+    \"be.doeraene\"  %%% \"scalajs-jquery\" % \"0.8.1\",
+    \"org.monifu\"   %%  \"minitest\"       % \"0.14\" % \"test\"
   ),
   crossTarget in Compile <<= baseDirectory(_ / \"..\" / \"..\" / \"assets\" / \"js\")
 ).enablePlugins(ScalaJSPlugin)" > ${current_dir}/_skinny_scalajs_settings.sbt
@@ -80,22 +80,28 @@ if [ "$command" == "new" ]; then
     echo "Usage: ./skinny new [application name]"
     exit 1
   fi
-  mkdir -p ${name}
-  cd ${name}
-  # TODO: download
-  yo skinny
-
-  echo " ******************************************** "
-  echo "   New Skinny application has been created!"
-  echo ""
-  echo "   $ cd ./${name}"
-  echo "   $ ./skinny run"
-  echo ""
-  echo "   Enjoy Scala programming!"
-  echo ""
-  echo " ******************************************** "
-  echo ""
-
+  if [ -d "$script_dir/skinny-blank-app" ]; then
+    cp -pr $script_dir/skinny-blank-app $name
+    echo " ******************************************** "
+    echo "   New Skinny application has been created!"
+    echo ""
+    echo "   $ cd ./${name}"
+    echo "   $ ./skinny run"
+    echo ""
+    echo "   Enjoy Scala programming!"
+    echo ""
+    echo " ******************************************** "
+    echo ""
+  else
+    echo " ******************************************** "
+    echo "   !!! ERROR !!!"
+    echo ""
+    echo "   skinny new command is unsupported when running local skinny script."
+    echo '   Run `brew install skinny` and then use the global script.'
+    echo ""
+    echo " ******************************************** "
+    exit 1
+  fi
 elif [ "$command" == "run" -o "$command" == "s" -o "$command" == "server" ]; then
   option="$2"
   if [ "$option" == "-precompile" -o "$option" == "--precompile" ]; then
@@ -176,7 +182,7 @@ elif [ "$command" == "db:repair" ]; then
 elif [ "$command" == "eclipse" ]; then
   setting_file="${current_dir}/project/_skinny_eclipse.sbt"
   if [ ! -f "${setting_file}" ]; then
-    echo "addSbtPlugin(\"com.typesafe.sbteclipse\" % \"sbteclipse-plugin\" % \"2.4.0\")" > ${setting_file} 
+    echo "addSbtPlugin(\"com.typesafe.sbteclipse\" % \"sbteclipse-plugin\" % \"4.0.0\")" > ${setting_file}
   fi
   ${sbt_path} eclipse
 elif [ "$command" == "idea" -o "$command" == "gen-idea" ]; then
@@ -188,15 +194,9 @@ elif [ "$command" == "package" ]; then
 elif [ "$command" == "package:standalone" ]; then
   setting_file="${current_dir}/project/_skinny_assembly.sbt"
   if [ ! -f "${setting_file}" ]; then
-    echo "addSbtPlugin(\"com.eed3si9n\" % \"sbt-assembly\" % \"0.11.2\")" > ${setting_file} 
-    echo "import AssemblyKeys._
-
-assemblySettings
-
-mainClass in assembly := Some(\"skinny.standalone.JettyLauncher\")
-
+    echo "addSbtPlugin(\"com.eed3si9n\" % \"sbt-assembly\" % \"0.14.0\")" > ${setting_file}
+    echo "mainClass in assembly := Some(\"skinny.standalone.JettyLauncher\")
 _root_.sbt.Keys.test in assembly := {}
-
 resourceGenerators in Compile <+= (resourceManaged, baseDirectory) map { (managedBase, base) =>
   val webappBase = base / \"src\" / \"main\" / \"webapp\"
   for ( (from, to) <- webappBase ** \"*\" \`pair\` rebase(webappBase, managedBase / \"main/\") )
@@ -204,8 +204,7 @@ resourceGenerators in Compile <+= (resourceManaged, baseDirectory) map { (manage
     Sync.copy(from, to)
     to
   }
-}
-" > "${current_dir}/_skinny_assembly_settings.sbt"
+}" > "${current_dir}/_skinny_assembly_settings.sbt"
   fi
 
   setup_standalone_build
